### ISSUE TITLE
Error on Server Start

### ISSUE THREAD

**Issue by TommyJ1994** [OWASP/django-DefectDojo#303]
Hit this issue when starting the server using ` python manage.py runserver`. The app was working fine before updating to the latest master.

```
Unhandled exception in thread started by <function wrapper at 0x7f6652ed6758>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tjackman/security/tools/DefectDojo/dojo/models.py", line 1141, in <module>
    watson.register(Product)
AttributeError: 'function' object has no attribute 'register'

```

**Comment by grendel513** [comment]
@TommyJ1994 - I could also not replicate the issue.  I tried it with both an existing install and a fresh install and they both worked.  @devGregA suggestion to make sure you update all dependencies should resolve this.

To address the watson issue specifically you can check out https://github.com/etianen/django-watson/blob/master/CHANGELOG.markdown#120---03122015 - we have moved to this new import a while back in Dojo.
