### ISSUE TITLE
Empty attribute 'risk_acceptance' in restful findings-API

### ISSUE THREAD

**Issue by no-sec-marko** [OWASP/django-DefectDojo#337]
Hi,

I setup a clean install of the defect dojo using the ./setup.bash (master branch) on the following system:

> DISTRIB_ID=CENTOS
> DISTRIB_RELEASE=7
> Django 1.11.2
> Dojo v1.1.4

and additionally setup near-production conditions using nginx, celery and uwsgi following the guide "https://github.com/OWASP/django-DefectDojo/blob/master/docs/dojo-production.rst"

After adding some findings in a sample test, I want the receive the issues by using the RESTful api "findings" (https://host.com/api/v1/findings/). The service response with the following error code:
```
{
  "error": "The model '&lt;Finding: Disclosure of folder/directory structure&gt;' has an empty attribute 'risk_acceptance' and doesn't allow a null value."
}
```
A debug session identified the error in the tastypie lib /usr/lib/python2.7/site-packages/tastypie/fields.py line 858:
```
if the_m2ms is None:
            if not self.null:
                raise ApiFieldError("The model '%r' has an empty attribute '%s' and doesn't allow a null value." % (previous_obj, attr))
```

and arise in the dojo/api.py code _class FindingResource(BaseModelResource)_ in line 495 and 523.

```
 492 class FindingResource(BaseModelResource):
 493     reporter = fields.ForeignKey(UserResource, 'reporter', null=False)
 494     test = fields.ForeignKey(TestResource, 'test', null=False)
 495     risk_acceptance = fields.ManyToManyField(RiskAcceptanceResource, 'risk_acceptance', full=False, null=False)
 496     product = fields.ForeignKey(ProductResource, 'test__engagement__product', full=False, null=False) 

[TRUNCATED]

 521             'out_of_scope': ALL,
 522             'duplicate': ALL,
 523             'risk_acceptance': ALL,
 524             'engagement': ALL_WITH_RELATIONS,

```

After commented out these both lines, the api call works find (as workaround). Unfortunately, I was not able to fix the described behaviour. Hopefully, you can reproduce the issue :)

**Comment by devGregA** [comment]
@aaronweaver would your latest revision also address this?

**Comment by aaronweaver** [comment]
@devGregA Not sure, I'll have to check.

**Comment by devGregA** [comment]
@no-sec-marko are you able to pull the new changes / test easily?

**Comment by no-sec-marko** [comment]
Hi @devGregA,

after update to the latest version 7bc6695, I receive the following error by requesting the API:

> Internal Server Error: /api/v1/doc/schema/findings
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 155, in get
    context = self.get_context_data(**kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie_swagger/views.py", line 138, in get_context_data
    'apis': mapping.build_apis(),
  File "/usr/lib/python2.7/site-packages/tastypie_swagger/mapping.py", line 411, in build_apis
    apis = [self.build_list_api(), self.build_detail_api()]
  File "/usr/lib/python2.7/site-packages/tastypie_swagger/mapping.py", line 383, in build_list_api
    list_api['operations'].append(self.build_list_operation(method='get'))
  File "/usr/lib/python2.7/site-packages/tastypie_swagger/mapping.py", line 334, in build_list_operation
    'parameters': self.build_parameters_for_list(method=method),
  File "/usr/lib/python2.7/site-packages/tastypie_swagger/mapping.py", line 147, in build_parameters_for_list
    parameters = self.build_parameters_from_filters(method=method)
  File "/usr/lib/python2.7/site-packages/tastypie_swagger/mapping.py", line 203, in build_parameters_from_filters
    has_related_resource = hasattr(self.resource.fields[name], 'get_related_resource')
KeyError: 'risk_acceptance'

**Comment by devGregA** [comment]
@no-sec-marko believe it is now fixed via @aaronweaver's PR https://github.com/OWASP/django-DefectDojo/pull/406

**Comment by no-sec-marko** [comment]
@devGregA yes, I try it with the latest version 3078f60 and it was fixed
